### ISSUE TITLE
Doesn't show current courses already registered for back in April

### ISSUE THREAD

**Issue by PatrickJazzMea** [gravitylow/OpenCourse#3]

**Comment by gravitylow** [comment]
The site has no access to CNU Live and is totally independent of that system in terms of registration. That is, OpenCourse cannot see whether you have actually registered for a course on CNU Live. So you can think of the schedule system as a planned schedule.

With that said, I am thinking about making a browser plugin that can help sync this information in the future.

**Comment by gravitylow** [comment]
The browser plugin has been created and is online! Check out: https://opencourseproject.com/about/#getting-started
Thanks for the suggestion.
