### ISSUE TITLE
Authentication cancelation not handled

### ISSUE THREAD

**Issue by HeroicLemon** [gravitylow/OpenCourse#4]
Directed to error page when clicking the cancel button while authenticating login: http://opencourseproject.com/complete/google-oauth2/?error=access_denied&state=ZCMkexkkRJfVd6ch95WMowkJSx0kBmJy#

Steps to reproduce:
Navigate to Login Page. Click Login to begin Google Authentication.
Select account to use for authentication (if applicable).
On Account Permissions page, click Cancel instead of Accept.

**Comment by gravitylow** [comment]
Thanks for the report. This is a prime example of an awesome bug report and I appreciate you taking the time to give reproduction steps and information detailed enough to fix it right off the bat. It goes a long way.

There should be an error page displayed when you visit the URL you mentioned or you follow the steps you gave. Give it a shot and double-check for me!

**Comment by HeroicLemon** [comment]
No problem. Looks like you've got it fixed now, nice project.
